### PR TITLE
Fix syntax warning over comparison of literals using is.

### LINKED ISSUE #25: Syntax warning due to comparison of literals using is in Python 3.8
```
find . -iname '*.py' | grep -v example | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./wiremock/base/base_resource.py:150: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif sc is 401:  # pragma: no cover
./wiremock/base/base_resource.py:152: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif sc is 403:  # pragma: no cover
./wiremock/base/base_resource.py:154: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif sc is 404:  # pragma: no cover
./wiremock/base/base_resource.py:156: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif sc is 422:  # pragma: no cover
./wiremock/base/base_resource.py:160: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif 400 <= sc < 500 and sc is not 404:  # pragma: no cover
```

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #25

### CODE REVIEW

**Review by platinummonkey — APPROVED** [review]
thanks for this! ❤️

**Comment by platinummonkey** [comment]
I'll cut a release here in a few minutes after $work thing :D

**Comment by tirkarthi** [comment]
Thanks for the review and merge :)

**Comment by platinummonkey** [comment]
released, `2.1.2`

**Pull request merged**
