### PR TITLE
Removing setuptools dependency on build

### PR DESCRIPTION
**Pull request by jmdacruz**
With the use of modern build tools such as `pyproject.toml` and `poetry`, there's no need to use `setuptools` and `setup.py` to build the distribution

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Should setup.py be removed from the repository entirely then?

**Comment by oleg-nenashev** [comment]
FTR it is used in the docs build flow too 

image

**Comment by jmdacruz** [comment]
Good catch! Yes, that should be replaced with 'poetry install'. I'll update the PR

**Comment by jmdacruz** [comment]
@oleg-nenashev I just updated the PR, but note that the command noted on the screenshot is not what's used to build the docs, but just a reference on how to install wiremock. I replaced that with a `poetry install` command. The doc builder script uses a different tool that is not referenced on `pyproject.toml`:

```shell
#!/bin/bash

sphinx-build docs html
watchmedo shell-command -R --command 'sphinx-build docs html' ./docs/
```

**Comment by gyoganathan** [comment]
@jmdacruz Can we go ahead and remove the setup.py file now?

**Comment by jmdacruz** [comment]
@gyoganathan we could, but the file currently doesn't influence the build using "Python -m build --sdist", meaning that the build using poetry does not depend on the "setup.py" file at all.

I'll let the authors decide if we should remove it in this PR

**Comment by jmdacruz** [comment]
@oleg-nenashev I went ahead and removed `setup.py`, since it's no longer referenced anywhere.

**Review by oleg-nenashev — APPROVED** [review]
Yes, thanks a lot! We can always restore it from the commit history should be needed

**Comment by jmdacruz** [comment]
@oleg-nenashev got your approval, but I can't merge yet. Do we need some other approval?

**Comment by oleg-nenashev** [comment]
Generally needs @mikeywaites to merge it as a maintainer

**Pull request merged**
